name: ci

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 设置环境变量
        uses: final-actions/set-up-env@main
        with:
          docker: true
          docker-registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: 部署
        uses: final-actions/kuboard-cicd@main
        with:
          host: ${{ secrets.KUBOARD_HOST }}
          username: ${{ secrets.KUBOARD_USERNAME }}
          access-key: ${{ secrets.KUBOARD_ACCESS_KEY }}
          namespace: default
          app-name: ${{ env.APP_NAME }}
          image: ${{ env.VERSION }}
          version: ${{ env.VERSION }}